### ISSUE TITLE
use badged.net badges instead?

### ISSUE THREAD

**Issue by gianpaj** [EmbraceAGI/Awesome-AGI#1]
I would say it's easier to read

<img width="791" alt="image" src="https://github.com/EmbraceAGI/Awesome-AGI/assets/899175/b2505286-b5bf-4e2e-bf77-a7814cbb18c4">

<https://badgen.net/github/stars/Significant-Gravitas/Auto-GPT>

![badge](https://badgen.net/github/stars/Significant-Gravitas/Auto-GPT)

https://badgen.net/

**Comment by yzfly** [comment]
Thank your for your great advice! The README.md is updated alreadly!
